spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: resources/other.yml
          # reference: https://stackoverflow.com/a/54559309
          search-locations: '[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]'

  #docker run -d --hostname spring-cloud-rabbit --name spring-cloud-rabbit -p 25672:15672 -p 5672:5672 rabbitmq:3-management
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh

server:
  port: 9905

logging:
  level:
    root: INFO

