
app:
  local:
    prop:
      value: Specific Application Name 5 Dev Profile
  server:
    prop:
      value: Specific Application Name 5 Dev Profile
  common:
    prop:
      value: Specific Application Name 5 Dev Profile
